/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockPoolSol from "./MockPool.sol";
export type { mockPoolSol };
export type { MockERC20 } from "./MockERC20";
export type { MockStrategy } from "./MockStrategy";
