/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as aerodromeStrategySol from "./AerodromeStrategy.sol";
export type { aerodromeStrategySol };
export type { AaveV3Strategy } from "./AaveV3Strategy";
export type { SimpleYieldStrategy } from "./SimpleYieldStrategy";
