/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAerodromeGauge,
  IAerodromeGaugeInterface,
} from "../../../../contracts/strategies/AerodromeStrategy.sol/IAerodromeGauge";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAerodromeGauge__factory {
  static readonly abi = _abi;
  static createInterface(): IAerodromeGaugeInterface {
    return new Interface(_abi) as IAerodromeGaugeInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAerodromeGauge {
    return new Contract(address, _abi, runner) as unknown as IAerodromeGauge;
  }
}
